#!/bin/sh

PHP_BIN=${phpbin:-"php-fpm"}
FPM_STATUS_URL=${fpm_status_url:-"fpm=http://localhost/fpm-status"}

function autoconf {
	which "$PHP_BIN" > /dev/null 2>&1 && echo yes || echo no
	exit 0
}

function fpm_pids {
	for pid in $(pidof "$PHP_BIN"); do
		cmdline=$(cat /proc/$pid/cmdline)
		if echo "$cmdline" | grep -qE "^php-fpm: pool "; then
			pool=${cmdline:14}
			echo $pool $pid
		fi
	done | sort
}

function get_pool_status {
	URL="$1"
	wget -qO- "$URL"
}
